pipeline {
    agent any

    stages {

        stage('Deploy to EKS') {
            steps {
                sh """
                kubectl apply -f deployment.yaml
                kubectl set image deployment/reviewapp reviewapp=innovativeacademy/reviewapp:${BUILD_NUMBER}
                """
            }
        }

    }
}
